packages:
    - name: geonode
      shared: false
      functions:
        - name: geonode
          binary: false
          main: ""
          runtime: python:default
          web: true
          environment:
            GEO_SERVER_URL: "${GEO_SERVER_URL}"
            GEO_SERVER_PORT: "${GEO_SERVER_PORT}"
